/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ofx;

import com.socket.Message;
import com.socket.SocketClient;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import static ofx.Ofx.tb;
import static ofx.loginn.username;

/**
 *
 * @author umang gupta
 */
public class Edit extends javax.swing.JFrame {
public Home ui;
public SocketClient client;
public int index; 
/**
     * Creates new form Edit
     */
    public Edit(Home ui) {
        this.ui=ui;       
        this.setVisible(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        itemname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descript = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Box1 = new javax.swing.JCheckBox();
        Box2 = new javax.swing.JCheckBox();
        Box3 = new javax.swing.JCheckBox();
        Box4 = new javax.swing.JCheckBox();
        Box5 = new javax.swing.JCheckBox();
        Box6 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText(" ItemName:");

        itemname.setEditable(false);

        jLabel2.setText("<html>Description:<br/>(optional)</html>");

        descript.setColumns(20);
        descript.setLineWrap(true);
        descript.setRows(5);
        descript.setToolTipText("Edit");
        descript.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descript);

        jLabel3.setText("Price:");

        jLabel4.setText("Rs");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("          Edit Search Tags");

        Box1.setText("Books");

        Box2.setText("Gadgets");

        Box3.setText("Formals");

        Box4.setText("Lab Practicals");

        Box5.setText("Hostels");

        Box6.setText("Miscellaneous");

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(itemname)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Box1)
                    .addComponent(Box4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Box2)
                            .addComponent(Box5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Box3)
                            .addComponent(Box6))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemname, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box1)
                    .addComponent(Box2)
                    .addComponent(Box3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box4)
                    .addComponent(Box5)
                    .addComponent(Box6))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        
    }                                     

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.client=ui.client;
       
         if(client!=null)
         {
          view_field view = new view_field();
            try {
                control_field ctrl = new control_field(view);
            } catch (IOException ex) {
                Logger.getLogger(AddItemn.class.getName()).log(Level.SEVERE, null, ex);
            }
        
         } 
         else
         {
             JOptionPane.showMessageDialog(tb, "connection failure");
         }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Box1;
    private javax.swing.JCheckBox Box2;
    private javax.swing.JCheckBox Box3;
    private javax.swing.JCheckBox Box4;
    private javax.swing.JCheckBox Box5;
    private javax.swing.JCheckBox Box6;
    private javax.swing.JTextArea descript;
    private javax.swing.JTextField itemname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
private class control_field {
           
     private view_field  view;

        public control_field(view_field viewnew) throws IOException {
 
            view=viewnew;
           //fetch fields
             String[] arr=new String[10];
            arr[1]=view.get_Itemname();
            arr[2]=view.get_Descript();
            arr[3]=view.get_Price();
            String[] checked =Arrays.copyOf(view.get_Tags(), view.get_Tags().length);
            for(int i=4;i<10;i++)
                arr[i]=checked[i-4];
            
            for(int i=4;i<10;i++)
            {
              System.out.println(arr[i]);
            }
            arr[0]=""+index;
             //pass arguments
         client.send(new Message("updateitem", username, arr, "SERVER"));
            
        }  
       
    }
    private class view_field {
    
   public ArrayList<JCheckBox> checkboxes;
        public String get_Itemname()
        {
            return itemname.getText();
        }
        public String get_Descript()
        {
            return descript.getText();
        }
        public String get_Price()
        {
            String Price=price.getText();
            return Price;
            /*if(Price.equals(""))
                return 0;
            return Integer.parseInt(Price);
                    */
        }
        public String[] get_Tags()
        {
            /*
           boolean[] arr=new boolean[6];//or   Boolean[] array = new Boolean[size];Arrays.fill(array, Boolean.FALSE); 
          */ checkboxes= new ArrayList<JCheckBox>();
          checkboxes.add(Box1);checkboxes.add(Box2);checkboxes.add(Box3);checkboxes.add(Box4);checkboxes.add(Box5);checkboxes.add(Box6);
          String[] arr=new String[6]; 
          Arrays.fill(arr,"0");
            for(int i=0;i<checkboxes.size();i++)
          {
              if(checkboxes.get(i).isSelected())
              {
                  arr[i]="1";
                  System.out.println((i+1)+"marked");
              }
          }
          return arr;
        }
    }
    
    public void fillframe(String item,String description,String cost,String box1,String box2,String box3,String box4,String box5,String box6,int index){
        if(box1.equals("1"))
                Box1.setSelected(true);
        if(box2.equals("1"))
                Box2.setSelected(true);
        if(box3.equals("1"))
                Box3.setSelected(true);
        if(box4.equals("1"))
                Box4.setSelected(true);
        if(box5.equals("1"))
                Box5.setSelected(true);
        if(box6.equals("1"))
                Box6.setSelected(true);
        itemname.setText(item);
        descript.setText(description);
        price.setText(cost);
        this.index=index;
    }
}
