/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ofx;

import com.socket.Message;
import com.socket.SocketClient;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static ofx.Ofx.tb;

/**
 *
 * @author umang gupta
 */
public class loginn extends javax.swing.JPanel {
 public static String username="", password="";
 public Home ui; 
 public SocketClient client;
 public static boolean check=false;
 /**
     * Creates new form loginn
     */
    public loginn(Home ui) {
        initComponents();
        this.ui=ui;
        forgotpanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        logbut = new javax.swing.JButton();
        forgot = new javax.swing.JLabel();
        forgotpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SecComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        answer = new javax.swing.JPasswordField();
        userf = new javax.swing.JTextField();
        newpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        confpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        setPreferredSize(new java.awt.Dimension(454, 386));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText(" Username:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText(" Password:");

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        logbut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logbut.setText("Login");
        logbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbutActionPerformed(evt);
            }
        });

        forgot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        forgot.setText("forgot your password?");
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotMouseClicked(evt);
            }
        });

        jLabel3.setText("Security Question:");

        SecComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "what is the name of your first pet?", "who was your first teacher?", "what city was your father born in?", "what is your mother's middle name?", "what was the name of the first school you attended?" }));

        jLabel4.setText("Answer:");

        jLabel5.setText("Username:");

        jLabel6.setText("New Password:");

        jLabel7.setText("Confirm password:");

        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forgotpanelLayout = new javax.swing.GroupLayout(forgotpanel);
        forgotpanel.setLayout(forgotpanelLayout);
        forgotpanelLayout.setHorizontalGroup(
            forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotpanelLayout.createSequentialGroup()
                .addGroup(forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotpanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(confpass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(newpass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(answer, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(forgotpanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        forgotpanelLayout.setVerticalGroup(
            forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotpanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(forgotpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(confpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(logbut)
                .addGap(126, 126, 126)
                .addComponent(forgot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(forgotpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logbut)
                    .addComponent(forgot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseClicked
        // TODO add your handling code here:
         if(!check)
        {
            forgotpanel.setVisible(true);
            check=true;
        }
        else
        {
            forgotpanel.setVisible(false);
            check=false;
        }
    }//GEN-LAST:event_forgotMouseClicked

    private void logbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbutActionPerformed
            // TODO add your handling code here:
            this.client=ui.client;
            if(client!=null)
         {
            view_field view = new view_field();
            try {
                control_field ctrl = new control_field(view);
            } catch (IOException ex) {
                Logger.getLogger(loginn.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
             else
         {
             JOptionPane.showMessageDialog(tb, "connection failure");
         }
    }//GEN-LAST:event_logbutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

          this.client=ui.client;
       
         if(client!=null)
         {
             view_fieldf view = new view_fieldf();
        try {
                  control_fieldf ctrl = new control_fieldf( view);
                 } catch (IOException ex) {
                     Logger.getLogger(loginn.class.getName()).log(Level.SEVERE, null, ex);
                 }
         }
            else
         {
             JOptionPane.showMessageDialog(tb, "connection failure");
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox SecComboBox;
    private javax.swing.JPasswordField answer;
    private javax.swing.JPasswordField confpass;
    private javax.swing.JLabel forgot;
    public static javax.swing.JPanel forgotpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JButton logbut;
    private javax.swing.JPasswordField newpass;
    public javax.swing.JPasswordField pass;
    public javax.swing.JTextField user;
    private javax.swing.JTextField userf;
    // End of variables declaration//GEN-END:variables
 
    private class control_field {
   
     private view_field  view;

        public control_field( view_field viewnew) throws IOException {
           
            view=viewnew;
            String[] arr=new String[1];
           //fetch fields
            
            String sender=view.get_User();
            arr[0]=view.get_Pass();
                    
        // pass arguments
             client.send(new Message("login", sender, arr, "SERVER"));   
            
        }  
       
    }
 private class view_field {
    
        public String get_User()
        {
            return user.getText();
        }
         public String get_Pass(){
            return (new String(pass.getPassword()));
        }
        
    }

   
    private class control_fieldf {
   
     private view_fieldf  view;

        public control_fieldf( view_fieldf viewnew) throws IOException {
           
            view=viewnew;
            String[] arr=new String[4];
           //fetch fields
            String userfor=view.get_User();
            arr[0]=view.get_Sec();
            arr[1]=view.get_Answer();
            arr[2]=view.get_Newpass();
            arr[3]=view.get_Confpass();
 
        //pass arguments
             client.send(new Message("updatepass", userfor, arr, "SERVER"));   
        }  
       
    }
 private class view_fieldf {
    
        public String get_User()
        {
            return userf.getText();
        }
         public String get_Answer(){
            return (new String(answer.getPassword()));
        }
          public String get_Newpass(){
            return (new String(newpass.getPassword()));
        }
           public String get_Confpass(){
            return (new String(confpass.getPassword()));
        }
           public String get_Sec(){
            return (""+SecComboBox.getSelectedIndex());
        }
 
    }

}
