/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ofx;

import com.socket.Message;
import com.socket.SocketClient;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;
import static ofx.loginn.username;


/**
 *
 * @author umang gupta
 */
public class Ofx extends javax.swing.JFrame {
  public static Ofx tb;
   private  Home p1;
   private Registern p2;
   public static loginn p3;
   private AddItemn p4;
    public static Chat p5;
     private SearchItemn p6;
     private Update p7;
     private Notifications p8;
     public NewItems ni;
     public Searchhistory sh;
     public static Edit editframe;
    public SocketClient client;
    public Thread clientThread;
    /**
     * Creates new form Home
     */
    public Ofx() {
        initComponents();
        this.setTitle("Messenger");
        
        this.addWindowListener(new WindowListener() {

            @Override public void windowOpened(WindowEvent e) {}
            @Override public void windowClosing(WindowEvent e) { 
                client=p1.client;clientThread=p1.clientThread;
                if(client!=null||clientThread!=null)
                {
              
                String[] content=new String[1];
                content[0]=".bye";
                try{ client.send(new Message("message", username, content, "SERVER")); clientThread.stop();  }catch(Exception ex){} 
                   }
                }
            @Override public void windowClosed(WindowEvent e) {}
            @Override public void windowIconified(WindowEvent e) {}
            @Override public void windowDeiconified(WindowEvent e) {}
            @Override public void windowActivated(WindowEvent e) {}
            @Override public void windowDeactivated(WindowEvent e) {}
        });
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpane = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabpane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabpane.setPreferredSize(new java.awt.Dimension(454, 388));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(128, 0, 128));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ofx/images/oe-150x80.jpg"))); // NOI18N
        jLabel2.setText("                                Offline Exchange");
        jLabel2.setPreferredSize(new java.awt.Dimension(19, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(tabpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabpane, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ofx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ofx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ofx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ofx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              tb= new Ofx();
             
                tb.setVisible(true);
                 tb.creategui();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane tabpane;
    // End of variables declaration//GEN-END:variables
  
   private void creategui(){
            
         p1=new Home();
         editframe=new Edit(p1);
           p2=new Registern(p1);
            p3=new loginn(p1);
             p4=new AddItemn(p1);
             p5=new Chat(p1);
             p6=new SearchItemn(p1);
               p7=new Update(p1,editframe);
               p8=new Notifications(p1);
               ni=new NewItems(p1);
               sh=new Searchhistory(p1);
        tabpane.addTab("  Home  ", null, p1,
                "Home");
        tabpane.setMnemonicAt(0, KeyEvent.VK_H);
        
        
          tabpane.addTab(" Register ",  null, p2,
                "Register");
        tabpane.setMnemonicAt(1, KeyEvent.VK_R);
         
       
             tabpane.addTab("  Login  ",  null, p3,
                "Login");
        tabpane.setMnemonicAt(2, KeyEvent.VK_L);
        
             tabpane.addTab(" AddItem ",  null, p4,
                "Add Item");
        tabpane.setMnemonicAt(3, KeyEvent.VK_A);
        
             tabpane.addTab("  Chat  ",  null, p5,
                "Chat");
        tabpane.setMnemonicAt(4, KeyEvent.VK_C);
        
        tabpane.addTab(" SearchItem ",  null, p6,
                "Search Items");
        tabpane.setMnemonicAt(5, KeyEvent.VK_S);
        
         tabpane.addTab(" Upadte ",  null, p7,
                "Update Inventory");
        tabpane.setMnemonicAt(6, KeyEvent.VK_U);
  
        tabpane.addTab(" Notifications ",  null, p8,
                "Notifications");
        tabpane.setMnemonicAt(7, KeyEvent.VK_N);
         ImageIcon icon = createImageIcon("images/images.jpg");
         tabpane.addTab(" NewItems ", icon, ni,
                "New Items");
          tabpane.addTab(" Hstory ",  null, sh,
                "Search History");
  
}
 protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL =Ofx.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
     
}
